2024-10-02 00:08:28.835 | INFO     | src.utils.logging_utils:wrapper:17 - Starting train_and_test
2024-10-02 00:08:28.835 | INFO     | __main__:train_and_test:63 - Initializing data module
2024-10-02 00:08:28.838 | INFO     | __main__:train_and_test:66 - Initializing model
2024-10-02 00:08:28.840 | ERROR    | src.utils.logging_utils:wrapper:23 - Error in train_and_test: Error locating target 'src.models.timm_classifier.TimmClassifier', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model
Traceback (most recent call last):

  File "/workspace/DogClassifier-Hydra/.venv/lib/python3.12/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
                  │    └ 'timm_classifier'
                  └ <module 'src.models' (namespace) from ['/workspace/DogClassifier-Hydra/src/models']>

AttributeError: module 'src.models' has no attribute 'timm_classifier'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/workspace/DogClassifier-Hydra/.venv/lib/python3.12/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
          │             └ 'src.models.timm_classifier'
          └ <function import_module at 0x7fcd2fb1cea0>
  File "/home/gitpod/.pyenv/versions/3.12.6/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'src.models.timm_classifier'
           │          └ <function _gcd_import at 0x7fcd300300e0>
           └ <module '_frozen_importlib' (frozen)>
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'src.models.timm_classifier'


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/workspace/DogClassifier-Hydra/.venv/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
             │       └ 'src.models.timm_classifier.TimmClassifier'
             └ <function _locate at 0x7fcd2f660ea0>
  File "/workspace/DogClassifier-Hydra/.venv/lib/python3.12/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(

ImportError: Error loading 'src.models.timm_classifier.TimmClassifier':
ModuleNotFoundError("No module named 'src.models.timm_classifier'")
Are you sure that 'timm_classifier' is importable from module 'src.models'?


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/workspace/DogClassifier-Hydra/src/train.py", line 115, in <module>
    main()
    └ <function main at 0x7fcce59bf380>

  File "/workspace/DogClassifier-Hydra/.venv/lib/python3.12/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
    └ <function _run_hydra at 0x7fcd2f660a40>
  File "/workspace/DogClassifier-Hydra/.venv/lib/python3.12/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
    └ <function _run_app at 0x7fcd2f660ae0>
  File "/workspace/DogClassifier-Hydra/.venv/lib/python3.12/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
    └ <function run_and_report at 0x7fcd2f6609a0>
  File "/workspace/DogClassifier-Hydra/.venv/lib/python3.12/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
           └ <function _run_app.<locals>.<lambda> at 0x7fcce59eba60>
  File "/workspace/DogClassifier-Hydra/.venv/lib/python3.12/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
            │     └ <function Hydra.run at 0x7fcd2f4f4360>
            └ <hydra._internal.hydra.Hydra object at 0x7fcce5b90a70>
  File "/workspace/DogClassifier-Hydra/.venv/lib/python3.12/site-packages/hydra/_internal/hydra.py", line 119, in run
    ret = run_job(
          └ <function run_job at 0x7fcd2f60b920>
  File "/workspace/DogClassifier-Hydra/.venv/lib/python3.12/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
    │   │              │             └ {'task_name': 'train', 'tags': ['dev'], 'train': True, 'test': True, 'ckpt_path': None, 'seed': 42, 'data': {'_target_': 'src...
    │   │              └ <function main at 0x7fcce59bf2e0>
    │   └ <property object at 0x7fcd2f5cefc0>
    └ JobReturn(overrides=['experiment=catdog_ex', 'model=tim_classify'], cfg={'task_name': 'train', 'tags': ['dev'], 'train': True...

  File "/workspace/DogClassifier-Hydra/src/train.py", line 112, in main
    train_and_test(config)
    │              └ {'task_name': 'train', 'tags': ['dev'], 'train': True, 'test': True, 'ckpt_path': None, 'seed': 42, 'data': {'_target_': 'src...
    └ <function train_and_test at 0x7fcce59bf1a0>

> File "/workspace/DogClassifier-Hydra/src/utils/logging_utils.py", line 19, in wrapper
    result = func(*args, **kwargs)
             │     │       └ {}
             │     └ ({'task_name': 'train', 'tags': ['dev'], 'train': True, 'test': True, 'ckpt_path': None, 'seed': 42, 'data': {'_target_': 'sr...
             └ <function train_and_test at 0x7fcce59bf100>

  File "/workspace/DogClassifier-Hydra/src/train.py", line 67, in train_and_test
    model = hydra.utils.instantiate(config.model)
            │     │     │           └ {'task_name': 'train', 'tags': ['dev'], 'train': True, 'test': True, 'ckpt_path': None, 'seed': 42, 'data': {'_target_': 'src...
            │     │     └ <function instantiate at 0x7fcd2f661260>
            │     └ <module 'hydra.utils' from '/workspace/DogClassifier-Hydra/.venv/lib/python3.12/site-packages/hydra/utils.py'>
            └ <module 'hydra' from '/workspace/DogClassifier-Hydra/.venv/lib/python3.12/site-packages/hydra/__init__.py'>

  File "/workspace/DogClassifier-Hydra/.venv/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           └ <function instantiate_node at 0x7fcd2f6613a0>
  File "/workspace/DogClassifier-Hydra/.venv/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
               │               │    │   │     │        └ 'model'
               │               │    │   │     └ <_Keys.TARGET: '_target_'>
               │               │    │   └ <enum '_Keys'>
               │               │    └ <function DictConfig.get at 0x7fcd2f751800>
               │               └ {'_target_': 'src.models.timm_classifier.TimmClassifier', 'model_name': 'resnet18', 'num_classes': 2, 'pretrained': True, 'lr...
               └ <function _resolve_target at 0x7fcd2f6611c0>
  File "/workspace/DogClassifier-Hydra/.venv/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
          │                      └ "Error locating target 'src.models.timm_classifier.TimmClassifier', set env var HYDRA_FULL_ERROR=1 to see chained exception.\...
          └ <class 'hydra.errors.InstantiationException'>

hydra.errors.InstantiationException: Error locating target 'src.models.timm_classifier.TimmClassifier', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model
